### ISSUE TITLE
PHP 7.2 Warning count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by juancarlosestradanieto** [miroc/Laravel-Adminer#20]
When I click on foreign key id in a table the browser crash and laravel throws an exception in adminer-4.3.1-en.php (line 1808). I think it is solved in new versions of adminer, so it would be fine if the versión of adminer is updated in this páckage.

**Comment by proseLA** [comment]
i experienced the same error when adding a new item.  using php7.2.

**Comment by proseLA** [comment]
worked for me too!  thanks.

**Comment by juancarlosestradanieto** [comment]
Great! You're welcome.

**Comment by BlueTeck** [comment]
@miroc please merge #17

**Comment by miroc** [comment]
Sorry guys for late answer, I just merged the request.
