### ISSUE TITLE
Throws error on PHP 7

### ISSUE THREAD

**Issue by JesseLeite** [miroc/Laravel-Adminer#5]
This version of adminer throws error on PHP 7.  I've been told that newer version of adminer has addressed the issue.

**Comment by miroc** [comment]
Thanks for a feedback! Looks like I need to update...

**Comment by miroc** [comment]
Should be fixed, I updated to Adminer 4.2.3 plus I integrated this pull request (got the same error with php7):
https://github.com/vrana/adminer/pull/153

**Comment by JesseLeite** [comment]
@miroc Thanks!  ...Though upon trying to update, it seems Packagist is still on an older commit.

**Comment by miroc** [comment]
@JesseLeite You're right. I updated that as well and will set up a push hook-up.

**Comment by JesseLeite** [comment]
Works on PHP 7, thanks <3
