### ISSUE TITLE
Update of Adminer to latest version

### ISSUE THREAD

**Issue by schonhose** [miroc/Laravel-Adminer#7]
I am using your package and it works great. Could you be so kind to update to the latest version of Adminer?

**Comment by EselDompteur** [comment]
+1 for that

**Comment by miroc** [comment]
I'm glad you like it, I'll update it today.

**Comment by miroc** [comment]
Updated to 4.2.4

**Comment by schonhose** [comment]
How can I update the package in Laravel with this new version?

**Comment by miroc** [comment]
Sorry I forgot to push it to Packagist. Now try to run `composer update`

**Comment by schonhose** [comment]
Thanks!
