### ISSUE TITLE
Automatic login for Laravel database

### ISSUE THREAD

**Issue by schonhose** [miroc/Laravel-Adminer#8]
Adminer can also automatically log in to the laravel database using the provided credentials from Laravel. 

From what I see you can also override the login form to display the Laravel credentials by default. This makes it possible for users to switch if needed.

See for example this [WP plugin](https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/shared-hosting-aid/adminer-wp-autologin/adminer-wp-login.php)

**Comment by miroc** [comment]
So if I understand that correctly, you want to take database login credentials from .env file and pre-fill it in Adminer login page or login directly, is that right?

**Comment by schonhose** [comment]
I am not sure if you should use the .env file or the settings from the config/database.php file. From what I understand is that the credentials in the .env file are transferred to the variables in config/database.php and those are used throughout laravel.

**Comment by miroc** [comment]
You can pre-fill server, username and database inputs from GET parameters. Pre-filling password is probably not a good idea.
To login directly, we would need to send POST request from PHP to Laravel route, I'm not sure if this is possible. Otherwise, some hacking of Adminer is required (as in the wordpress script), but unfortunately I don't have time for that at the moment. If you want to, try to implement it, I can merge it later.

**Comment by jonasof** [comment]
Here is one quick fix solution:

Create a controller extending \Miroc\LaravelAdminer\AdminerController, and pass login info in constructor to $_GET and $_POST.

```
<?php

namespace App\Http\Controllers;

class Adminer extends \Miroc\LaravelAdminer\AdminerController
{
    public function __construct()
    {
        $database_config = config('database.default');

        $database_driver = config("database.connections.$database_config.driver");
        if ($database_driver === "mysql")
            $database_driver = "server";

        if (! isset($_GET['db'])) {
            $_POST['auth']['driver'] = $database_driver;
            $_POST['auth']['server'] = config("database.connections.$database_config.host");
            $_POST['auth']['db'] = config("database.connections.$database_config.database");
            $_POST['auth']['username'] = config("database.connections.$database_config.username");
            $_POST['auth']['password'] = config("database.connections.$database_config.password");
        }
        
    } 
}

```

and of course add the route:
`Route::any('/adminer', 'Adminer@index');`

I have tested with sqlite and postgresql and works. It auto-login to the same database in use by Laravel, and you can't logout.

**Comment by miroc** [comment]
Thanks for a solution, this looks good. I'm thinking of adding this as a separate controller into the package, wouldn't you mind? (or you create a pull request) Let's call the controller AdminerAutologinController.
